// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitPrefix
{
    internal sealed partial class Vsix
    {
        public const string Id = "GitPrefix.41d9aced-bfd8-451b-a56d-7dab6c5fab9c";
        public const string Name = "GitPrefix";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Organization";
        public const string Tags = "";
    }
}
