// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitPrefix
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GitPrefixString = "bb70f522-d446-42f9-8466-7d13d0793095";
        public static Guid GitPrefix = new Guid(GitPrefixString);

        public const string GitMenuString = "57735d06-c920-4415-a2e0-7d6e6fbdfa99";
        public static Guid GitMenu = new Guid(GitMenuString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GitPrefixGroup = 0x0001;
        public const int AppendGitPrefix = 0x0100;
        public const int menuidGitTopLevelMenu = 0xF000;
    }
}
